# Read .npy file

In [1]:
import numpy as np
from pathlib import Path

# CPC pre-training dataset path
# memmap_file = Path("./ecg_data_processed/ribeiro_fs100/memmap.npy")
# meta_file = Path("./ecg_data_processed/ribeiro_fs100/memmap_meta.npz")

# # # # CPC fine-tune dataset path
# memmap_file = Path("./ecg_data_processed/ptb_xl_fs100/memmap.npy")
# meta_file = Path("./ecg_data_processed/ptb_xl_fs100/memmap_meta.npz")


# HY2DL pre-training dataset path
memmap_file = r"D:\Research\Projects\CPC2HY\ecg_data_processed\hy2dl_pre_train\memmap.npy"
meta_file = r"D:\Research\Projects\CPC2HY\ecg_data_processed\hy2dl_pre_train\memmap_meta.npz"

# HY2DL fine-tune dataset path
# memmap_file = r"D:\Research\Projects\CPC2HY\ecg_data_processed\hy2dl_fine_tune\memmap.npy"
# meta_file = r"D:\Research\Projects\CPC2HY\ecg_data_processed\hy2dl_fine_tune\memmap_meta.npz"


# 1. 加载元数据
meta = np.load(meta_file, allow_pickle=True)
start = meta["start"]
length = meta["length"]
shape = meta["shape"]
file_idx = meta["file_idx"]
dtype = np.dtype(str(meta["dtype"]))
print("dataset shape: ", shape)  # the first element is total length (sequence lenghth * num_samples), the second is feature dimension (12 for ECG)

# 2. 打开 memmap 文件
memmap_data = np.memmap(memmap_file, dtype=dtype, mode='r', shape=tuple(shape[0]))

# # 3. 访问第一个样本（示例）
idx = 0
sample_start = start[idx]
sample_length = length[idx]
print("No. samples: ", len(start))

sample = memmap_data[sample_start : sample_start + sample_length]
print("One sample shape:", sample.shape)
print("The first 5 timesteps of this sample: ", sample[:5, :])  # 显示前5个时间步的12维数据

dataset shape:  [[5475   22]]
No. samples:  15
One sample shape: (365, 22)
The first 5 timesteps of this sample:  [[-0.42654595 -0.44271308 -0.75636005 -0.57028174 -0.5510159  -0.6418174
   0.30368382 -0.9832141   0.8735651  -0.7678422  -0.57735026 -0.6469754
   0.640841    0.          0.         -0.89504695  1.072222   -0.09491571
  -0.07193203 -0.14177522  0.          0.        ]
 [-0.33011258 -0.2826597  -0.94753003 -0.49257046 -0.47647172 -0.6418174
   0.30368382 -0.9832141   0.8735651  -0.7678422  -0.57735026 -0.6469754
   0.640841    0.          0.         -0.89504695  1.072222   -0.09491571
  -0.07193203 -0.14177522  0.          0.        ]
 [-0.23944874  0.05136469 -1.2039505  -0.36422905 -0.19071886 -0.6418174
   0.30368382 -0.9832141   0.8735651  -0.7678422  -0.57735026 -0.6469754
   0.640841    0.          0.         -0.89504695  1.072222   -0.09491571
  -0.07193203 -0.14177522  0.          0.        ]
 [-0.5312215  -0.51926035 -0.74670255 -0.2523719  -0.13688137 -0.6418174


In [2]:
print("==== Keys in meta file ====")
print(meta.files)

print("\n==== Content ====")
for key in meta.files:
    print(f"\n--- {key} ---")
    print(meta[key])

==== Keys in meta file ====
['start', 'length', 'shape', 'file_idx', 'dtype', 'filenames']

==== Content ====

--- start ---
[   0  365  730 1095 1460 1825 2190 2555 2920 3285 3650 4015 4380 4745
 5110]

--- length ---
[365 365 365 365 365 365 365 365 365 365 365 365 365 365 365]

--- shape ---
[[5475   22]]

--- file_idx ---
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

--- dtype ---
float32

--- filenames ---
['./memmap.npy']


# Read .pickle file

In [1]:
import pickle

# 你的 df_memmap.pkl 路径
# pkl_file = "./ecg_data_processed/ptb_xl_fs100/df_memmap.pkl"
# pkl_file = "./ecg_data_processed/ptb_xl_fs100/df.pkl"
# pkl_file = "./ecg_data_processed/ptb_xl_fs100/lbl_itos.pkl"

pkl_file = r"D:\Research\Projects\Hy2DL\results\LSTM_CAMELS_DE_seed_110\scaler.pickle"

with open(pkl_file, "rb") as f:
    content = pickle.load(f)

print("Loaded object type:", type(content))

# 如果是 list 或 tuple，打印长度
if isinstance(content, (list, tuple)):
    print("Length:", len(content))
    for i, item in enumerate(content):
        print(f"[{i}] type={type(item)}")
else:
    print("Content keys:" if hasattr(content, 'keys') else "Content:", content)

Loaded object type: <class 'dict'>
Content keys: {'x_d_mean': {'precipitation_mean': tensor(6.4452), 'precipitation_stdev': tensor(0.7462), 'radiation_global_mean': tensor(122.7680), 'temperature_min': tensor(1.8716), 'temperature_max': tensor(10.5934)}, 'x_d_std': {'precipitation_mean': tensor(12.1327), 'precipitation_stdev': tensor(1.4370), 'radiation_global_mean': tensor(80.7658), 'temperature_min': tensor(7.2440), 'temperature_max': tensor(8.4930)}, 'y_mean': tensor([5.6129]), 'y_std': tensor([10.0506]), 'x_s_mean': tensor([2.9747e+01, 1.1380e+03, 2.6180e+01, 3.4793e+01, 3.8923e+01, 1.0967e+00,
        1.2523e+01, 8.6380e+01, 0.0000e+00, 0.0000e+00, 5.2033e+00, 2.5333e-01,
        1.7333e-01, 1.5393e+01, 1.9811e+02, 1.1800e+00, 3.8600e+00]), 'x_s_std': tensor([1.5217e+01, 1.7388e+02, 3.0512e-01, 2.0567e+00, 1.8276e+00, 1.8995e+00,
        1.9202e+01, 2.1097e+01, 1.0000e+00, 1.0000e+00, 5.0649e-01, 8.0829e-02,
        3.5119e-02, 7.4144e-01, 5.3606e+00, 1.0000e+00, 1.0000e+00])}
